# Generated by Django 5.0.6 on 2024-06-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearAuto',
            new_name='Auto',
        ),
    ]
